export const PERMISSIONS = {
  DASHBOARD_VIEW_FULL: 'dashboard.view.full',
  DASHBOARD_VIEW_SCOPED: 'dashboard.view.scoped',
  OPERATIONS_VIEW_ALL: 'operations.view.all',
  OPERATIONS_VIEW_CLASS: 'operations.view.class',
  OPERATIONS_VIEW_FINANCE: 'operations.view.finance',
  OPERATIONS_VIEW_DOCUMENTS: 'operations.view.documents',
  STUDENTS_VIEW_ALL: 'students.view.all',
  STUDENTS_EDIT_ALL: 'students.edit.all',
  STUDENTS_VIEW_HOMEROOM: 'students.view.homeroom',
  STUDENTS_EDIT_HOMEROOM: 'students.edit.homeroom',
  STUDENTS_VIEW_FEE_STATUS: 'students.view.fee_status',
  STUDENTS_VIEW_BASIC: 'students.view.basic',
  TEACHERS_VIEW_FULL: 'teachers.view.full',
  TEACHERS_MANAGE: 'teachers.manage',
  DOCUMENTS_MANAGE_ALL: 'documents.manage.all',
  DOCUMENTS_VIEW: 'documents.view',
  DOCUMENTS_UPLOAD_FEE: 'documents.upload.fee',
  DOCUMENTS_UPLOAD_ALL: 'documents.upload.all',
  FEES_MANAGE: 'fees.manage',
  FEES_VIEW: 'fees.view',
  FEES_RECONCILE: 'fees.reconcile',
  TIMETABLE_MANAGE: 'timetable.manage',
  TIMETABLE_VIEW: 'timetable.view',
  ATTENDANCE_VIEW_ALL: 'attendance.view.all',
  ATTENDANCE_MARK_HOMEROOM: 'attendance.mark.homeroom',
  AI_COMMAND_CENTER: 'ai.command_center',
  USERS_MANAGE_ALL: 'users.manage.all',
  SYSTEM_SETTINGS: 'system.settings',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  'Super Admin': [...Object.values(PERMISSIONS), 'superadmin.only'],

  'Principal': [
    PERMISSIONS.DASHBOARD_VIEW_FULL,
    PERMISSIONS.OPERATIONS_VIEW_ALL,
    PERMISSIONS.STUDENTS_VIEW_ALL,
    PERMISSIONS.STUDENTS_EDIT_ALL,
    PERMISSIONS.TEACHERS_VIEW_FULL,
    PERMISSIONS.TEACHERS_MANAGE,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.TIMETABLE_MANAGE,
    PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.ATTENDANCE_MARK_HOMEROOM,
    PERMISSIONS.AI_COMMAND_CENTER,
  ],

  'Class Teacher': [
    PERMISSIONS.DASHBOARD_VIEW_SCOPED,
    PERMISSIONS.OPERATIONS_VIEW_CLASS,
    PERMISSIONS.STUDENTS_VIEW_HOMEROOM,
    PERMISSIONS.STUDENTS_EDIT_HOMEROOM,
    PERMISSIONS.TIMETABLE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK_HOMEROOM,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.FEES_VIEW,
  ],

  'Accountant': [
    PERMISSIONS.DASHBOARD_VIEW_SCOPED,
    PERMISSIONS.OPERATIONS_VIEW_FINANCE,
    PERMISSIONS.STUDENTS_VIEW_FEE_STATUS,
    PERMISSIONS.DOCUMENTS_UPLOAD_FEE,
    PERMISSIONS.FEES_MANAGE,
    PERMISSIONS.FEES_RECONCILE,
  ],

  'Receptionist': [
    PERMISSIONS.DASHBOARD_VIEW_SCOPED,
    PERMISSIONS.OPERATIONS_VIEW_DOCUMENTS,
    PERMISSIONS.STUDENTS_VIEW_BASIC,
    PERMISSIONS.DOCUMENTS_UPLOAD_ALL,
    PERMISSIONS.DOCUMENTS_VIEW,
  ],

  // PHASE 2 Placeholders
  'Vice Principal': [PERMISSIONS.DASHBOARD_VIEW_FULL, PERMISSIONS.OPERATIONS_VIEW_ALL],
  'Subject Teacher': [PERMISSIONS.DASHBOARD_VIEW_SCOPED, PERMISSIONS.TIMETABLE_VIEW],
  'Exam Coordinator': [PERMISSIONS.DASHBOARD_VIEW_SCOPED, PERMISSIONS.STUDENTS_VIEW_ALL],
  'IT Support': [PERMISSIONS.DASHBOARD_VIEW_SCOPED, PERMISSIONS.SYSTEM_SETTINGS, PERMISSIONS.USERS_MANAGE_ALL],
  'Librarian': [PERMISSIONS.DASHBOARD_VIEW_SCOPED],
  'Counselor': [PERMISSIONS.DASHBOARD_VIEW_SCOPED],
  'Transport Manager': [PERMISSIONS.DASHBOARD_VIEW_SCOPED],
  'Security Guard': [PERMISSIONS.DASHBOARD_VIEW_SCOPED],
  'Student': [PERMISSIONS.DASHBOARD_VIEW_SCOPED],
  'Parent': [PERMISSIONS.DASHBOARD_VIEW_SCOPED]
};
